# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\35170\Desktop\Developments\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1030, 700))
        MainWindow.setMaximumSize(QtCore.QSize(9999, 9999))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(242, 254, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(70, 30))
        self.label_8.setStyleSheet("color:rgb(67, 67, 67);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 20pt \"等线\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(90, 30))
        self.label_5.setStyleSheet("color:rgb(67, 67, 67);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 20pt \"等线\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_Phote = QtWidgets.QLabel(self.centralwidget)
        self.label_Phote.setMinimumSize(QtCore.QSize(740, 500))
        self.label_Phote.setMaximumSize(QtCore.QSize(9999, 99999))
        self.label_Phote.setStyleSheet("background-color:rgb(161, 161, 161)")
        self.label_Phote.setText("")
        self.label_Phote.setScaledContents(True)
        self.label_Phote.setObjectName("label_Phote")
        self.gridLayout_10.addWidget(self.label_Phote, 0, 1, 1, 6)
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setMaximumSize(QtCore.QSize(16777215, 30))
        self.output.setStyleSheet("color:rgb(255, 85, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 26pt \"楷体\";")
        self.output.setObjectName("output")
        self.gridLayout_10.addWidget(self.output, 1, 6, 1, 1)
        self.label_line_show = QtWidgets.QLabel(self.centralwidget)
        self.label_line_show.setMaximumSize(QtCore.QSize(50, 30))
        self.label_line_show.setStyleSheet("color:rgb(255, 85, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 26pt \"楷体\";")
        self.label_line_show.setObjectName("label_line_show")
        self.gridLayout_10.addWidget(self.label_line_show, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(70, 30))
        self.label_9.setStyleSheet("color:rgb(67, 67, 67);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 20pt \"等线\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_point_show = QtWidgets.QLabel(self.centralwidget)
        self.label_point_show.setMaximumSize(QtCore.QSize(50, 30))
        self.label_point_show.setStyleSheet("color:rgb(255, 85, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 75 26pt \"楷体\";")
        self.label_point_show.setObjectName("label_point_show")
        self.gridLayout_10.addWidget(self.label_point_show, 1, 4, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(280, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_data = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_data.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_data.setToolTip("")
        self.lineEdit_data.setStatusTip("")
        self.lineEdit_data.setWhatsThis("")
        self.lineEdit_data.setStyleSheet("QLineEdit{\n"
"\n"
"background-color:white;\n"
"border: 1px solid rgbrgb(121, 121, 121);\n"
"border-radius:5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"\n"
"background-color:white;\n"
"border: 1px solid rgb(81, 81, 81);\n"
"border-radius:5px\n"
"}\n"
"\n"
"QLineEdit:checked{\n"
"\n"
"background-color:white;\n"
"border: 1px solid rgb(34, 34, 34);\n"
"border-radius:5px\n"
"}\n"
"\n"
"")
        self.lineEdit_data.setInputMask("")
        self.lineEdit_data.setText("")
        self.lineEdit_data.setPlaceholderText("")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout.addWidget(self.lineEdit_data, 3, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Blurry = QtWidgets.QLabel(self.widget)
        self.label_Blurry.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_Blurry.setFont(font)
        self.label_Blurry.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_Blurry.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Blurry.setObjectName("label_Blurry")
        self.gridLayout_2.addWidget(self.label_Blurry, 1, 4, 1, 1)
        self.label_Median = QtWidgets.QLabel(self.widget)
        self.label_Median.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_Median.setFont(font)
        self.label_Median.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_Median.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Median.setObjectName("label_Median")
        self.gridLayout_2.addWidget(self.label_Median, 2, 4, 1, 1)
        self.label_Fit = QtWidgets.QLabel(self.widget)
        self.label_Fit.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_Fit.setFont(font)
        self.label_Fit.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.label_Fit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Fit.setObjectName("label_Fit")
        self.gridLayout_2.addWidget(self.label_Fit, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.Blurry_Slider = QtWidgets.QSlider(self.widget)
        self.Blurry_Slider.setMinimumSize(QtCore.QSize(0, 20))
        self.Blurry_Slider.setStyleSheet("QSlider {\n"
"    background-color:rgb(255, 170, 0);\n"
"    padding-right: 3px;\n"
"    padding-left: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(199, 199, 199);\n"
"    width:5px;\n"
"    border:1px solid rgb(165, 165, 165);\n"
"    border-radius: 2px;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"    background-color:rgb(124, 252, 171);\n"
"    width:5px;\n"
"    border:1px solid rgb(165, 165, 165);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background:transparent;\n"
"    height:8px\n"
"}\n"
" \n"
"QSlider::handle:horizontal {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius: 6px;\n"
"    background: white;\n"
"    border-image:url(\"进度.png\");\n"
"}")
        self.Blurry_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Blurry_Slider.setObjectName("Blurry_Slider")
        self.gridLayout_2.addWidget(self.Blurry_Slider, 1, 1, 1, 3)
        self.Fit_Slider = QtWidgets.QSlider(self.widget)
        self.Fit_Slider.setMinimumSize(QtCore.QSize(0, 20))
        self.Fit_Slider.setStyleSheet("QSlider {\n"
"    background-color:rgb(255, 170, 0);\n"
"    padding-right: 3px;\n"
"    padding-left: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(199, 199, 199);\n"
"    width:5px;\n"
"    border:1px solid rgb(165, 165, 165);\n"
"    border-radius: 2px;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"    background-color:rgb(124, 252, 171);\n"
"    width:5px;\n"
"    border:1px solid rgb(165, 165, 165);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background:transparent;\n"
"    height:8px\n"
"}\n"
" \n"
"QSlider::handle:horizontal {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius: 6px;\n"
"    background: white;\n"
"    border-image:url(\"进度.png\");\n"
"}")
        self.Fit_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Fit_Slider.setObjectName("Fit_Slider")
        self.gridLayout_2.addWidget(self.Fit_Slider, 0, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.Median_Slider = QtWidgets.QSlider(self.widget)
        self.Median_Slider.setMinimumSize(QtCore.QSize(0, 20))
        self.Median_Slider.setStyleSheet("QSlider {\n"
"    background-color:rgb(255, 170, 0);\n"
"    padding-right: 3px;\n"
"    padding-left: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(199, 199, 199);\n"
"    width:5px;\n"
"    border:1px solid rgb(165, 165, 165);\n"
"    border-radius: 2px;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"    background-color:rgb(124, 252, 171);\n"
"    width:5px;\n"
"    border:1px solid rgb(165, 165, 165);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background:transparent;\n"
"    height:8px\n"
"}\n"
" \n"
"QSlider::handle:horizontal {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius: 6px;\n"
"    background: white;\n"
"    border-image:url(\"进度.png\");\n"
"}")
        self.Median_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Median_Slider.setObjectName("Median_Slider")
        self.gridLayout_2.addWidget(self.Median_Slider, 2, 1, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 3)
        self.pushButton_Caculater = QtWidgets.QPushButton(self.widget)
        self.pushButton_Caculater.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Caculater.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_Caculater.setObjectName("pushButton_Caculater")
        self.gridLayout.addWidget(self.pushButton_Caculater, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 0, 0)")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_start.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 6, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tabWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_PP_S_nextpoint = QtWidgets.QPushButton(self.tab)
        self.pushButton_PP_S_nextpoint.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_PP_S_nextpoint.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_PP_S_nextpoint.setObjectName("pushButton_PP_S_nextpoint")
        self.gridLayout_7.addWidget(self.pushButton_PP_S_nextpoint, 2, 2, 1, 1)
        self.pushButton_PP_S_lastpoint = QtWidgets.QPushButton(self.tab)
        self.pushButton_PP_S_lastpoint.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_PP_S_lastpoint.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_PP_S_lastpoint.setObjectName("pushButton_PP_S_lastpoint")
        self.gridLayout_7.addWidget(self.pushButton_PP_S_lastpoint, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(0, 20))
        self.label_12.setStyleSheet("image:url(\"点.png\")")
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.pushButton_PP_F_nextpoint = QtWidgets.QPushButton(self.tab)
        self.pushButton_PP_F_nextpoint.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_PP_F_nextpoint.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_PP_F_nextpoint.setObjectName("pushButton_PP_F_nextpoint")
        self.gridLayout_7.addWidget(self.pushButton_PP_F_nextpoint, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setStyleSheet("image:url(\"线.png\")")
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 2, 1, 1)
        self.pushButton_PP_F_lastpoint = QtWidgets.QPushButton(self.tab)
        self.pushButton_PP_F_lastpoint.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_PP_F_lastpoint.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_PP_F_lastpoint.setObjectName("pushButton_PP_F_lastpoint")
        self.gridLayout_7.addWidget(self.pushButton_PP_F_lastpoint, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 0, 1, 3, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_LL_S_lastline = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_LL_S_lastline.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_LL_S_lastline.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_LL_S_lastline.setObjectName("pushButton_LL_S_lastline")
        self.gridLayout_6.addWidget(self.pushButton_LL_S_lastline, 1, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_6.addWidget(self.line_4, 0, 1, 3, 1)
        self.pushButton_LL_F_nextline = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_LL_F_nextline.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_LL_F_nextline.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_LL_F_nextline.setObjectName("pushButton_LL_F_nextline")
        self.gridLayout_6.addWidget(self.pushButton_LL_F_nextline, 2, 0, 1, 1)
        self.pushButton_LL_F_lastline = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_LL_F_lastline.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_LL_F_lastline.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_LL_F_lastline.setObjectName("pushButton_LL_F_lastline")
        self.gridLayout_6.addWidget(self.pushButton_LL_F_lastline, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setStyleSheet("image:url(\"线.png\")")
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 2, 1, 1)
        self.pushButton_LL_S_nextline = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_LL_S_nextline.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_LL_S_nextline.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_LL_S_nextline.setObjectName("pushButton_LL_S_nextline")
        self.gridLayout_6.addWidget(self.pushButton_LL_S_nextline, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setStyleSheet("image:url(\"点.png\")")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_lastPoint = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_lastPoint.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_lastPoint.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_lastPoint.setObjectName("pushButton_lastPoint")
        self.gridLayout_5.addWidget(self.pushButton_lastPoint, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setStyleSheet("image:url(\"点.png\")")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 0, 1, 3, 1)
        self.pushButton_nextPoint = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_nextPoint.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_nextPoint.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_nextPoint.setObjectName("pushButton_nextPoint")
        self.gridLayout_5.addWidget(self.pushButton_nextPoint, 2, 0, 1, 1)
        self.pushButton_nextLine = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_nextLine.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_nextLine.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_nextLine.setObjectName("pushButton_nextLine")
        self.gridLayout_5.addWidget(self.pushButton_nextLine, 2, 2, 1, 1)
        self.pushButton_lastLine = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_lastLine.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_lastLine.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_lastLine.setObjectName("pushButton_lastLine")
        self.gridLayout_5.addWidget(self.pushButton_lastLine, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setStyleSheet("image:url(\"线.png\")")
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 3)
        self.label_pixel = QtWidgets.QLabel(self.widget)
        self.label_pixel.setStyleSheet("background-color:rgb(255, 255, 0)")
        self.label_pixel.setObjectName("label_pixel")
        self.gridLayout.addWidget(self.label_pixel, 10, 1, 1, 1)
        self.speed_show_label = QtWidgets.QLabel(self.widget)
        self.speed_show_label.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.speed_show_label.setObjectName("speed_show_label")
        self.gridLayout.addWidget(self.speed_show_label, 6, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_camera = QtWidgets.QPushButton(self.widget)
        self.pushButton_camera.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_camera.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.gridLayout_9.addWidget(self.pushButton_camera, 0, 0, 1, 1)
        self.pushButton_take = QtWidgets.QPushButton(self.widget)
        self.pushButton_take.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_take.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_take.setObjectName("pushButton_take")
        self.gridLayout_9.addWidget(self.pushButton_take, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 0, 2, 1, 1)
        self.label_camera = QtWidgets.QLabel(self.widget)
        self.label_camera.setMinimumSize(QtCore.QSize(260, 195))
        self.label_camera.setMaximumSize(QtCore.QSize(260, 195))
        self.label_camera.setStyleSheet("background-color:rgb(188, 188, 188)")
        self.label_camera.setText("")
        self.label_camera.setObjectName("label_camera")
        self.gridLayout_9.addWidget(self.label_camera, 1, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_9, 11, 0, 1, 3)
        self.pushButton_data = QtWidgets.QPushButton(self.widget)
        self.pushButton_data.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_data.setFont(font)
        self.pushButton_data.setStyleSheet("QPushButton\n"
"{\n"
"color:rgb(48, 48, 48);\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"    font: 11pt \"Calibri\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-color: rgb(85, 255, 255);\n"
"border:1px solid rgb(165, 165, 165);\n"
"background-color:rgb(207, 207, 207);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(186, 186, 186); \n"
"    padding-left:1px; \n"
"    padding-top:2px;\n"
"}")
        self.pushButton_data.setObjectName("pushButton_data")
        self.gridLayout.addWidget(self.pushButton_data, 4, 1, 1, 1)
        self.comboBox_duibi = QtWidgets.QComboBox(self.widget)
        self.comboBox_duibi.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_duibi.setStyleSheet("QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1px solid rgb(222, 222, 222);\n"
"    font: 10pt \"黑体\";\n"
"\n"
"\n"
"}\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  right ;\n"
"     \n"
"     width :  20px ;\n"
" \n"
"     border-left-width :  1px ;\n"
"     border-left-color : darkgray;\n"
"     border-left-style :  solid ;  /* just a single line */\n"
"     border-top-right-radius:  3px ;  /* same radius as the QComboBox */\n"
"     border-bottom-right-radius:  3px ;\n"
"}\n"
"QComboBox::drop-down::hover{\n"
"background-color:rgb(182, 182, 182)\n"
"}\n"
"QComboBox::down-arrow {\n"
"     border-image:url(\"下拉.png\");\n"
"}")
        self.comboBox_duibi.setObjectName("comboBox_duibi")
        self.comboBox_duibi.addItem("")
        self.comboBox_duibi.addItem("")
        self.gridLayout.addWidget(self.comboBox_duibi, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget, 0, 0, 2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoVisualDetection"))
        self.label_8.setText(_translate("MainWindow", "点："))
        self.label_5.setText(_translate("MainWindow", "边线:"))
        self.output.setText(_translate("MainWindow", "0.00000"))
        self.label_line_show.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "距："))
        self.label_point_show.setText(_translate("MainWindow", "0"))
        self.label_Blurry.setText(_translate("MainWindow", "15"))
        self.label_Median.setText(_translate("MainWindow", "100"))
        self.label_Fit.setText(_translate("MainWindow", "5"))
        self.label_2.setToolTip(_translate("MainWindow", "高斯模糊卷积参数，Blurry越高精度越低"))
        self.label_2.setText(_translate("MainWindow", "Blurry"))
        self.label_4.setToolTip(_translate("MainWindow", "拟合精度，Fit越低精度越高"))
        self.label_4.setText(_translate("MainWindow", "Fit"))
        self.label_3.setToolTip(_translate("MainWindow", "取二值图时的阈值"))
        self.label_3.setText(_translate("MainWindow", "Median"))
        self.pushButton_Caculater.setText(_translate("MainWindow", "Caculater"))
        self.label.setToolTip(_translate("MainWindow", "像素尺寸转换比"))
        self.label.setText(_translate("MainWindow", "Parameter"))
        self.pushButton_start.setText(_translate("MainWindow", "start"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_PP_S_nextpoint.setText(_translate("MainWindow", "next point"))
        self.pushButton_PP_S_lastpoint.setText(_translate("MainWindow", "last point"))
        self.label_12.setText(_translate("MainWindow", "line 1"))
        self.pushButton_PP_F_nextpoint.setText(_translate("MainWindow", "next point"))
        self.label_13.setText(_translate("MainWindow", "line 2"))
        self.pushButton_PP_F_lastpoint.setText(_translate("MainWindow", "last point"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "p_p"))
        self.pushButton_LL_S_lastline.setText(_translate("MainWindow", "last line"))
        self.pushButton_LL_F_nextline.setText(_translate("MainWindow", "next line"))
        self.pushButton_LL_F_lastline.setText(_translate("MainWindow", "last line"))
        self.label_7.setText(_translate("MainWindow", "line 2"))
        self.pushButton_LL_S_nextline.setText(_translate("MainWindow", "next line"))
        self.label_6.setText(_translate("MainWindow", "line 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "L_L"))
        self.pushButton_lastPoint.setText(_translate("MainWindow", "Last point"))
        self.label_10.setText(_translate("MainWindow", "point"))
        self.pushButton_nextPoint.setText(_translate("MainWindow", "Next point"))
        self.pushButton_nextLine.setText(_translate("MainWindow", "Next line"))
        self.pushButton_lastLine.setText(_translate("MainWindow", "Last line"))
        self.label_11.setText(_translate("MainWindow", "line"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "P_L"))
        self.label_pixel.setText(_translate("MainWindow", "像素"))
        self.speed_show_label.setText(_translate("MainWindow", "速度"))
        self.pushButton_camera.setText(_translate("MainWindow", "Camera"))
        self.pushButton_take.setText(_translate("MainWindow", "Enter"))
        self.pushButton.setText(_translate("MainWindow", "shutdown"))
        self.pushButton_data.setText(_translate("MainWindow", "Lock"))
        self.comboBox_duibi.setItemText(0, _translate("MainWindow", "深色背景亮色物体"))
        self.comboBox_duibi.setItemText(1, _translate("MainWindow", "亮色背景深色物体"))
